
apiVersion: 1
contactPoints:
  - orgId: 1
    name: Discord CV Alerts
    receivers:
      - uid: discord-cv-webhook
        type: discord
        settings:
          url: https://discord.com/api/webhooks/1439929629539307604/ZrIlEhXi2mfj3RltyTO8nTlYhmiooaypFFG_pHQ9S3RK5hkXySdCr1x0FYtv7dyLnV8B
          use_discord_username: true
        disableResolveMessage: false